import org.jetbrains.compose.desktop.application.dsl.TargetFormat

plugins {
    kotlin("jvm")
    id("org.jetbrains.compose")
    id("org.jetbrains.kotlin.plugin.compose")
}

dependencies {
    implementation(project(":core"))
    implementation(compose.desktop.currentOs)
    implementation(compose.material3)
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.8.1")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-swing:1.8.1")
    implementation("org.json:json:20240303")
    // QR rendering for "pair from phone" — desktop shows, phone scans.
    implementation("com.google.zxing:core:3.5.3")
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}
kotlin {
    compilerOptions { jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17) }
}

// Write a tiny BuildVersion.kt so the running app can show its own SemVer in the UI
// without us hand-syncing strings. Drops into a generated source dir; participates in
// normal incremental compilation.
val genVersionDir = layout.buildDirectory.dir("generated/version/main")
val generateBuildVersion by tasks.registering {
    val outDir = genVersionDir
    val v = rootProject.extra["versionSemver"] as String
    outputs.dir(outDir)
    inputs.property("v", v)
    doLast {
        val pkgDir = outDir.get().asFile.resolve("net/tenbo/hubble/desktop").apply { mkdirs() }
        pkgDir.resolve("BuildVersion.kt").writeText(
            """
            package net.tenbo.hubble.desktop

            /** Auto-generated by the root build script from /VERSION + git. */
            object BuildVersion { const val SEMVER: String = "$v" }
            """.trimIndent() + "\n",
        )
    }
}
sourceSets["main"].kotlin.srcDir(genVersionDir)
tasks.named("compileKotlin") { dependsOn(generateBuildVersion) }

// Round-trips the OS keychain (store → retrieve → clear) so the integration can be verified
// on a real machine without driving the GUI.  ./gradlew :desktop:keychainCheck
tasks.register<JavaExec>("keychainCheck") {
    group = "verification"
    classpath = sourceSets["main"].runtimeClasspath
    mainClass.set("net.tenbo.hubble.desktop.KeychainCheckKt")
}

compose.desktop {
    application {
        mainClass = "net.tenbo.hubble.desktop.MainKt"
        nativeDistributions {
            targetFormats(TargetFormat.Dmg, TargetFormat.Msi, TargetFormat.Deb)
            packageName = "Hubble"
            // 3-part "MAJOR.MINOR.N" — installers reject SemVer pre-release suffixes.
            // Auto-derived from git via root build.gradle.kts; the strictly increasing
            // N gives Windows Installer auto-upgrade for free. macOS DMG additionally
            // requires MAJOR >= 1 (CFBundleShortVersionString), so override there.
            packageVersion = rootProject.extra["versionNumeric"] as String
            macOS {
                packageVersion = "1.0.${rootProject.extra["versionCode"]}"
            }
            // jlink strips everything not explicitly included; this list comes from
            // `./gradlew :desktop:suggestRuntimeModules`. Without java.net.http the app
            // crashes immediately ("Failed to launch JVM" → NoClassDefFoundError in
            // DesktopApi).
            modules("java.instrument", "java.naming", "java.net.http", "java.sql", "jdk.unsupported")
        }
    }
}
